name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build program
        run: |
          cd ${{ github.workspace }}
          gcc -o SimpleCProgram.c ./desktop/year3semester2/devops/devopslab5

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpleCProgram
          path: SimpleCProgram

