name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build program
        run: gcc -o SimpleCProgram "${{ github.workspace }}/.SimpleCProgram.c"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpleCProgram
          path: SimpleCProgram
